### PR TITLE
Factor out Constants

### PR DESCRIPTION
**Pull request by martypowell**
Web Services needs to be able to configure the app, based on resources in site executive. This moves the config from the app, to a script inside the site executive page properties.

### CODE REVIEW

**Review by ascire — APPROVED** [review]
You will probably still want to keep an out-of-box dev configuration for rapid debugging.

**Comment by martypowell** [comment]
@ascire whatchu talking about?

**Comment by ascire** [comment]
Did you remove all the config files out of the source or did you leave one around that you can debug against?

**Comment by martypowell** [comment]
@ascire they are all out, what needs to happen is the example page for this app needs to be updated with that config. This allows us to manually specify where the templates and data are, without "recompiling" the app

**Pull request merged**
